/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_usefulness_rootbeer_RootBeerNative */

#ifndef _Included_io_github_usefulness_rootbeer_RootBeerNative
#define _Included_io_github_usefulness_rootbeer_RootBeerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_usefulness_rootbeer_RootBeerNative
 * Method:    checkForRoot
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_usefulness_rootbeer_RootBeerNative_checkForRoot
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     io_github_usefulness_rootbeer_RootBeerNative
 * Method:    checkForMagiskUDS
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_usefulness_rootbeer_RootBeerNative_checkForMagiskUDS
  (JNIEnv *, jobject);

/*
 * Class:     io_github_usefulness_rootbeer_RootBeerNative
 * Method:    setLogDebugMessages
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_io_github_usefulness_rootbeer_RootBeerNative_setLogDebugMessages
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
